@extends('layouts.app')

@section('title', 'AI model monitoring')

@section('content')
    @php
        $model = $model ?? ['name' => 'Demand forecast', 'version' => '—', 'mape' => 0, 'rmse' => 0, 'last_trained_at' => '—', 'drift_detected' => false];
        $forecastHistory = $forecastHistory ?? [];
    @endphp
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-medium text-indigo-600">PLATFORM HEALTH · STEP 9</p><h1 class="mt-1 text-2xl font-semibold tracking-tight sm:text-[28px]">AI model monitoring</h1><p class="mt-1 text-sm text-slate-500">Track forecast quality and respond to shifts in demand.</p></div><form method="POST" action="{{ route('admin.ai-monitoring.retrain') }}">@csrf<button type="submit" class="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-indigo-600 px-4 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700"><span aria-hidden="true">↻</span>Trigger model retraining</button></form></div>
    @if ($model['drift_detected'])<div class="mt-6 flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4" role="alert"><span class="grid size-8 shrink-0 place-items-center rounded-full bg-amber-100 font-semibold text-amber-800">!</span><div><p class="text-sm font-semibold text-amber-900">Forecast drift detected</p><p class="mt-1 text-sm leading-5 text-amber-800">Recent forecast error is above the configured threshold. Review the affected regions and consider retraining the model.</p></div></div>@endif
    @if (session('retraining-status'))<div class="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800" role="status">{{ session('retraining-status') }}</div>@endif

    <section class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Model health metrics">
        <article class="rounded-2xl border border-slate-200/60 bg-white p-5 shadow-sm"><p class="text-sm font-medium text-slate-500">Forecast model</p><p class="mt-3 text-lg font-semibold tracking-tight">{{ $model['name'] }}</p><p class="mt-1 text-xs text-slate-500">Version {{ $model['version'] }}</p></article>
        <article class="rounded-2xl border border-slate-200/60 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><p class="text-sm font-medium text-slate-500">MAPE</p><span class="rounded-full {{ $model['mape'] <= ($thresholds['mape'] ?? 15) ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700' }} px-2 py-1 text-[10px] font-semibold">{{ $model['mape'] <= ($thresholds['mape'] ?? 15) ? 'Within range' : 'Above threshold' }}</span></div><p class="mt-3 text-3xl font-semibold tracking-tight tabular-nums">{{ number_format($model['mape'], 1) }}<span class="text-lg">%</span></p><p class="mt-1 text-xs text-slate-500">Mean absolute percentage error</p></article>
        <article class="rounded-2xl border border-slate-200/60 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><p class="text-sm font-medium text-slate-500">RMSE</p><span class="rounded-full {{ $model['rmse'] <= ($thresholds['rmse'] ?? 100) ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700' }} px-2 py-1 text-[10px] font-semibold">{{ $model['rmse'] <= ($thresholds['rmse'] ?? 100) ? 'Within range' : 'Above threshold' }}</span></div><p class="mt-3 text-3xl font-semibold tracking-tight tabular-nums">{{ number_format($model['rmse'], 1) }}</p><p class="mt-1 text-xs text-slate-500">Root mean square error · units</p></article>
        <article class="rounded-2xl border border-slate-200/60 bg-white p-5 shadow-sm"><p class="text-sm font-medium text-slate-500">Last trained</p><p class="mt-3 text-lg font-semibold tracking-tight">{{ $model['last_trained_at'] }}</p><p class="mt-1 text-xs text-slate-500">{{ $model['training_records'] ?? '—' }} evaluation samples</p></article>
    </section>

    <section class="mt-6 rounded-2xl border border-slate-200/60 bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><h2 class="text-base font-semibold tracking-tight">Forecast error over time</h2><p class="mt-1 text-sm text-slate-500">Actual vs. configured error limits, by evaluation period.</p></div><div class="flex gap-4 text-xs"><span class="inline-flex items-center gap-1.5 text-slate-600"><span class="size-2 rounded-full bg-indigo-500"></span>MAPE</span><span class="inline-flex items-center gap-1.5 text-slate-600"><span class="size-2 rounded-full bg-amber-400"></span>Drift threshold</span></div></div>
        <div class="mt-5 overflow-x-auto"><div class="min-w-[640px]"><svg viewBox="0 0 720 240" class="h-60 w-full" role="img" aria-label="Forecast error chart showing MAPE by evaluation period"><line x1="48" y1="20" x2="48" y2="200" stroke="#e2e8f0"/><line x1="48" y1="200" x2="700" y2="200" stroke="#e2e8f0"/><line x1="48" y1="80" x2="700" y2="80" stroke="#fbbf24" stroke-dasharray="5 5"/><text x="8" y="24" fill="#94a3b8" font-size="10">30%</text><text x="14" y="84" fill="#94a3b8" font-size="10">15%</text><text x="21" y="204" fill="#94a3b8" font-size="10">0%</text><text x="655" y="74" fill="#b45309" font-size="10">Drift limit</text>
            @if (count($forecastHistory) > 1)
                @php($points = collect($forecastHistory)->values()->map(function ($entry, $index) use ($forecastHistory) { $x = 48 + ($index * (652 / (count($forecastHistory) - 1))); $y = 200 - (min(30, max(0, $entry['mape'] ?? 0)) * 6); return round($x, 1).','.round($y, 1); })->implode(' '))
                <polyline points="{{ $points }}" fill="none" stroke="#6366f1" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
                @foreach ($forecastHistory as $index => $entry)<circle cx="{{ round(48 + ($index * (652 / (count($forecastHistory) - 1))), 1) }}" cy="{{ round(200 - (min(30, max(0, $entry['mape'] ?? 0)) * 6), 1) }}" r="4" fill="#6366f1"/>@endforeach
            @else
                <text x="360" y="115" text-anchor="middle" fill="#64748b" font-size="13">Forecast evaluation history will appear here</text>
            @endif
            </svg><div class="flex justify-between px-12 text-[10px] text-slate-400">@forelse ($forecastHistory as $entry)<span>{{ $entry['period'] ?? '—' }}</span>@empty<span>Evaluation periods</span>@endforelse</div></div></div>
    </section>

    <section class="mt-6 rounded-2xl border border-slate-200/60 bg-white p-5 shadow-sm sm:p-6"><div><h2 class="text-base font-semibold tracking-tight">Recent evaluation periods</h2><p class="mt-1 text-sm text-slate-500">Model performance measured against realized demand.</p></div><div class="mt-5 overflow-x-auto"><table class="w-full min-w-[540px] text-left text-sm"><thead class="border-b border-slate-100 text-[10px] font-semibold tracking-wide text-slate-400"><tr><th class="pb-3 pr-4">PERIOD</th><th class="pb-3 pr-4">EVALUATED FORECASTS</th><th class="pb-3 pr-4">MAPE</th><th class="pb-3 pr-4">RMSE</th><th class="pb-3">STATUS</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse (collect($forecastHistory)->reverse() as $entry)<tr><td class="py-3.5 pr-4 font-medium text-slate-800">{{ $entry['period'] ?? '—' }}</td><td class="py-3.5 pr-4 tabular-nums">{{ number_format($entry['sample_count'] ?? 0) }}</td><td class="py-3.5 pr-4 tabular-nums">{{ number_format($entry['mape'] ?? 0, 1) }}%</td><td class="py-3.5 pr-4 tabular-nums">{{ number_format($entry['rmse'] ?? 0, 1) }}</td><td class="py-3.5"><span class="rounded-full {{ ($entry['drift'] ?? false) ? 'bg-red-50 text-red-700' : 'bg-emerald-50 text-emerald-700' }} px-2.5 py-1 text-xs font-medium">{{ ($entry['drift'] ?? false) ? 'Drift detected' : 'Stable' }}</span></td></tr>@empty<tr><td colspan="5" class="py-10 text-center text-sm text-slate-500">No evaluation history available.</td></tr>@endforelse</tbody></table></div></section>
@endsection