@extends('layouts.app')

@section('title', 'Discrepancy tickets')

@section('content')
    @php($complaints = $complaints ?? collect())
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-medium text-red-700">SUPPLY OPERATIONS</p><h1 class="mt-1 text-2xl font-semibold tracking-tight sm:text-[28px]">Discrepancy tickets</h1><p class="mt-1 text-sm text-slate-500">Resolve cases created when dispatch and receipt quantities differ.</p></div><div class="flex gap-2"><span class="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-700">{{ $complaints->where('status', 'open')->count() }} open</span><span class="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700">{{ $complaints->where('status', 'resolved')->count() }} resolved</span></div></div>
    <section class="mt-6 rounded-2xl border border-slate-200/60 bg-white p-5 shadow-sm sm:p-6">
        <div class="flex flex-col gap-3 border-b border-slate-100 pb-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-base font-semibold tracking-tight">All tickets</h2><p class="mt-1 text-sm text-slate-500">Cases are linked to a distributor, dispatch record, and reported variance.</p></div><label><span class="sr-only">Filter by ticket status</span><select name="status" class="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100"><option value="all">All statuses</option><option value="open">Open</option><option value="investigating">Investigating</option><option value="resolved">Resolved</option></select></label></div>
        <div class="mt-5 overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead class="border-b border-slate-100 text-[10px] font-semibold tracking-wide text-slate-400"><tr><th class="pb-3 pr-4">TICKET</th><th class="pb-3 pr-4">DISTRIBUTOR</th><th class="pb-3 pr-4">DISPATCHED</th><th class="pb-3 pr-4">RECEIVED</th><th class="pb-3 pr-4">VARIANCE</th><th class="pb-3 pr-4">CREATED</th><th class="pb-3">STATUS</th></tr></thead><tbody class="divide-y divide-slate-100">
            @forelse ($complaints as $complaint)
                @php($record = is_array($complaint) ? $complaint : $complaint->toArray())
                <tr><td class="py-4 pr-4 font-semibold text-slate-800">{{ $record['reference'] ?? '—' }}<span class="mt-0.5 block text-xs font-normal text-slate-500">{{ $record['dispatch_reference'] ?? '—' }}</span></td><td class="py-4 pr-4 text-slate-700">{{ $record['distributor_name'] ?? '—' }}</td><td class="py-4 pr-4 tabular-nums">{{ number_format($record['dispatched_quantity'] ?? 0) }}</td><td class="py-4 pr-4 tabular-nums">{{ number_format($record['received_quantity'] ?? 0) }}</td><td class="py-4 pr-4"><span class="rounded-full bg-red-50 px-2.5 py-1 text-xs font-medium text-red-700">{{ number_format(($record['received_quantity'] ?? 0) - ($record['dispatched_quantity'] ?? 0)) }}</span></td><td class="py-4 pr-4 text-slate-500">{{ $record['created_at'] ?? '—' }}</td><td class="py-4">@if (($record['status'] ?? '') === 'resolved')<span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-medium text-emerald-700">Resolved</span>@else<form method="POST" action="{{ route('manager.complaints.resolve', $record['id']) }}">@csrf @method('PATCH')<button type="submit" class="rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-semibold text-slate-700 hover:border-emerald-200 hover:bg-emerald-50 hover:text-emerald-700">Resolve</button></form>@endif</td></tr>
            @empty
                <tr><td colspan="7" class="py-14 text-center"><span class="mx-auto grid size-11 place-items-center rounded-full bg-emerald-50 text-emerald-700">✓</span><p class="mt-3 text-sm font-semibold text-slate-800">No discrepancy tickets</p><p class="mt-1 text-xs text-slate-500">Automatically created cases will appear here.</p></td></tr>
            @endforelse
        </tbody></table></div>
    </section>
@endsection