@extends('layouts.app')

@section('title', 'Request review queue')

@section('content')
    @php($flaggedRequests = $flaggedRequests ?? collect())
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-medium text-amber-700">SUPPLY OPERATIONS · STEP 3</p><h1 class="mt-1 text-2xl font-semibold tracking-tight sm:text-[28px]">Request review queue</h1><p class="mt-1 text-sm text-slate-500">Review requests above the high forecast threshold.</p></div><span class="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-700">{{ $flaggedRequests->count() }} awaiting review</span></div>
    <section class="mt-6 rounded-2xl border border-slate-200/60 bg-white p-5 shadow-sm sm:p-6">
        <div class="flex flex-col gap-3 border-b border-slate-100 pb-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-base font-semibold tracking-tight">Flagged requests</h2><p class="mt-1 text-sm text-slate-500">Compare requested quantity (R) with the forecast high before approving.</p></div><label class="relative"><span class="sr-only">Filter requests</span><input type="search" name="filter" placeholder="Filter requests" class="h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 sm:w-56"></label></div>
        <div class="mt-5 overflow-x-auto"><table class="w-full min-w-[780px] text-left text-sm"><thead class="border-b border-slate-100 text-[10px] font-semibold tracking-wide text-slate-400"><tr><th class="pb-3 pr-4">REQUEST</th><th class="pb-3 pr-4">DISTRIBUTOR</th><th class="pb-3 pr-4">REQUESTED (R)</th><th class="pb-3 pr-4">FORECAST HIGH</th><th class="pb-3 pr-4">OVERAGE</th><th class="pb-3 pr-4">SUBMITTED</th><th class="pb-3">ACTION</th></tr></thead><tbody class="divide-y divide-slate-100">
            @forelse ($flaggedRequests as $request)
                @php($record = is_array($request) ? $request : $request->toArray())
                <tr><td class="py-4 pr-4 font-semibold text-slate-800">{{ $record['reference'] ?? '—' }}</td><td class="py-4 pr-4"><span class="block font-medium text-slate-800">{{ $record['distributor_name'] ?? '—' }}</span><span class="mt-0.5 block text-xs text-slate-500">{{ $record['location'] ?? '—' }}</span></td><td class="py-4 pr-4 tabular-nums">{{ number_format($record['requested_quantity'] ?? 0) }}</td><td class="py-4 pr-4 tabular-nums">{{ number_format($record['forecast_high'] ?? 0) }}</td><td class="py-4 pr-4"><span class="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-medium text-amber-700">+{{ number_format(max(0, ($record['requested_quantity'] ?? 0) - ($record['forecast_high'] ?? 0))) }}</span></td><td class="py-4 pr-4 text-slate-500">{{ $record['submitted_at'] ?? '—' }}</td><td class="py-4"><button type="button" data-request-id="{{ $record['id'] }}" data-request-reference="{{ $record['reference'] }}" data-request-quantity="{{ $record['requested_quantity'] }}" class="whitespace-nowrap rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:border-indigo-200 hover:bg-indigo-50 hover:text-indigo-700" onclick="const dialog=document.getElementById('review-dialog'); dialog.showModal(); document.getElementById('review-request-id').value=this.dataset.requestId; document.getElementById('review-request-reference').textContent=this.dataset.requestReference; document.getElementById('approved_qty').value=this.dataset.requestQuantity;">Review request</button></td></tr>
            @empty
                <tr><td colspan="7" class="py-14 text-center"><span class="mx-auto grid size-11 place-items-center rounded-full bg-emerald-50 text-emerald-700">✓</span><p class="mt-3 text-sm font-semibold text-slate-800">Queue is clear</p><p class="mt-1 text-xs text-slate-500">Flagged requests will appear here when submitted.</p></td></tr>
            @endforelse
        </tbody></table></div>
    </section>

    <dialog id="review-dialog" class="m-auto w-[min(100%-2rem,520px)] rounded-2xl border border-slate-200 bg-white p-0 shadow-2xl backdrop:bg-slate-950/30">
        <form method="POST" action="{{ route('manager.review-queue.review') }}" class="p-6">
            @csrf
            <div class="flex items-start justify-between gap-4"><div><p class="text-xs font-semibold text-indigo-600">REQUEST REVIEW</p><h2 class="mt-1 text-xl font-semibold tracking-tight">Review <span id="review-request-reference">request</span></h2><p class="mt-1 text-sm text-slate-500">Approve as requested or adjust the authorized quantity.</p></div><button type="button" onclick="document.getElementById('review-dialog').close()" class="grid size-9 place-items-center rounded-lg text-lg text-slate-400 hover:bg-slate-100" aria-label="Close review">×</button></div>
            <input type="hidden" id="review-request-id" name="demand_request_id">
            <div class="mt-5"><label for="approved_qty" class="mb-1.5 block text-sm font-medium text-slate-700">Approved quantity (A) <span class="text-red-600">*</span></label><input id="approved_qty" name="approved_qty" type="number" min="0" step="1" required class="h-11 w-full rounded-lg border border-slate-200 px-3 text-sm outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100">@error('approved_qty')<p class="mt-1.5 text-xs text-red-600">{{ $message }}</p>@enderror</div>
            <label class="mt-4 flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 p-3.5"><input type="checkbox" name="company_short_supply" value="1" class="mt-0.5 size-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"><span><span class="block text-sm font-medium text-slate-800">Company short supply exemption</span><span class="mt-0.5 block text-xs leading-5 text-slate-500">Record that limited company inventory affected the approved quantity.</span></span></label>
            <div class="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onclick="document.getElementById('review-dialog').close()" class="h-10 rounded-lg border border-slate-200 px-4 text-sm font-medium text-slate-700 hover:bg-slate-50">Cancel</button><button type="submit" name="decision" value="adjust" class="h-10 rounded-lg border border-slate-200 px-4 text-sm font-semibold text-slate-700 hover:bg-slate-50">Adjust quantity</button><button type="submit" name="decision" value="approve" class="h-10 rounded-lg bg-indigo-600 px-4 text-sm font-semibold text-white hover:bg-indigo-700">Approve request</button></div>
        </form>
    </dialog>
@endsection