<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
    <title>Record verification · {{ config('app.name', 'Optima Chain') }}</title>
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=instrument-sans:400,500,600,700" rel="stylesheet">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-slate-50 font-sans text-slate-900 antialiased">
    @php($record = $record ?? [])
    <header class="border-b border-slate-200 bg-white"><div class="mx-auto flex h-16 max-w-5xl items-center justify-between px-4 sm:px-6"><a href="{{ url('/') }}" class="flex items-center gap-2.5"><span class="grid size-8 place-items-center rounded-lg bg-indigo-600 font-bold text-white">O</span><span class="text-sm font-semibold tracking-tight">Optima<span class="text-indigo-600">Chain</span></span></a><span class="text-xs font-medium text-slate-500">Independent record verification · Step 8</span></div></header>
    <main class="mx-auto max-w-5xl px-4 py-8 sm:px-6 sm:py-12">
        <div class="mb-6"><p class="text-xs font-semibold tracking-wide text-indigo-600">BANK & PARTNER PORTAL</p><h1 class="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">Distributor record</h1><p class="mt-1 text-sm text-slate-500">Official verification of a supply-chain credit record.</p></div>
        <article class="relative overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div class="pointer-events-none absolute right-[-35px] top-[46%] rotate-[-25deg] select-none text-6xl font-bold tracking-tight text-slate-900/[0.035] sm:right-4 sm:text-8xl" aria-hidden="true">OPTIMA VERIFIED</div>
            <div class="relative border-b border-slate-200 bg-slate-50/80 p-5 sm:p-7"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div class="flex items-center gap-2"><span class="size-2 rounded-full {{ ($isVerified ?? false) ? 'bg-emerald-500' : 'bg-red-500' }}"></span><p class="text-xs font-semibold tracking-wide {{ ($isVerified ?? false) ? 'text-emerald-700' : 'text-red-700' }}">{{ ($isVerified ?? false) ? 'VERIFIED RECORD' : 'RECORD NOT VERIFIED' }}</p></div><h2 class="mt-2 text-xl font-semibold tracking-tight">{{ $record['distributor_name'] ?? 'Record unavailable' }}</h2><p class="mt-1 text-sm text-slate-500">{{ $record['legal_entity'] ?? 'No entity details available' }}</p></div><div class="rounded-xl border border-slate-200 bg-white px-4 py-3"><p class="text-[10px] font-semibold tracking-wide text-slate-400">RECORD ID</p><p class="mt-1 font-mono text-sm font-semibold text-slate-800">{{ $record['verification_code'] ?? request()->route('code') ?? '—' }}</p></div></div></div>
            <div class="relative p-5 sm:p-7"><div class="grid gap-6 sm:grid-cols-2 lg:grid-cols-4"><div><p class="text-xs text-slate-500">Registration ID</p><p class="mt-1.5 text-sm font-medium text-slate-800">{{ $record['registration_id'] ?? 'Not supplied' }}</p></div><div><p class="text-xs text-slate-500">Operating region</p><p class="mt-1.5 text-sm font-medium text-slate-800">{{ $record['region'] ?? 'Not supplied' }}</p></div><div><p class="text-xs text-slate-500">Record period</p><p class="mt-1.5 text-sm font-medium text-slate-800">{{ $record['period'] ?? 'Not supplied' }}</p></div><div><p class="text-xs text-slate-500">Verified on</p><p class="mt-1.5 text-sm font-medium text-slate-800">{{ $record['verified_at'] ?? 'Not supplied' }}</p></div></div>
                <div class="mt-8 border-t border-slate-100 pt-6"><div class="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><h3 class="text-sm font-semibold">Aggregated performance metrics</h3><p class="mt-1 text-xs text-slate-500">Metrics are aggregated for the record period shown above.</p></div><span class="rounded-full bg-indigo-50 px-2.5 py-1 text-[11px] font-medium text-indigo-700">{{ $record['grade'] ?? 'Grade unavailable' }}</span></div><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div class="rounded-xl border border-slate-200 p-4"><p class="text-xs text-slate-500">Credit score</p><p class="mt-2 text-2xl font-semibold tabular-nums">{{ isset($record['score']) ? number_format($record['score']).'/100' : '—' }}</p></div><div class="rounded-xl border border-slate-200 p-4"><p class="text-xs text-slate-500">Order accuracy</p><p class="mt-2 text-2xl font-semibold tabular-nums">{{ isset($record['accuracy']) ? number_format($record['accuracy'], 1).'%' : '—' }}</p></div><div class="rounded-xl border border-slate-200 p-4"><p class="text-xs text-slate-500">Fulfillment rate</p><p class="mt-2 text-2xl font-semibold tabular-nums">{{ isset($record['fulfillment_rate']) ? number_format($record['fulfillment_rate'], 1).'%' : '—' }}</p></div><div class="rounded-xl border border-slate-200 p-4"><p class="text-xs text-slate-500">On-time delivery</p><p class="mt-2 text-2xl font-semibold tabular-nums">{{ isset($record['on_time_rate']) ? number_format($record['on_time_rate'], 1).'%' : '—' }}</p></div></div></div>
                <div class="mt-8 border-t border-slate-100 pt-6"><h3 class="text-sm font-semibold">Cryptographic integrity</h3><p class="mt-1 text-xs text-slate-500">Use this hash to confirm the record contents have not changed.</p><div class="mt-3 break-all rounded-lg bg-slate-50 px-4 py-3 font-mono text-xs leading-6 text-slate-600">{{ $record['cryptographic_hash'] ?? 'Hash unavailable for this record' }}</div></div>
            </div>
            <footer class="relative border-t border-slate-200 bg-slate-50/80 px-5 py-4 sm:px-7"><div class="flex flex-col justify-between gap-2 sm:flex-row sm:items-center"><p class="text-xs leading-5 text-slate-500">This verification reflects the record at the time shown. It is not a guarantee of future performance or a lending decision.</p><p class="shrink-0 text-xs font-medium text-slate-500">Issued by Optima Chain</p></div></footer>
        </article>
    </main>
    <footer class="mx-auto max-w-5xl px-4 pb-8 text-center text-[11px] text-slate-400 sm:px-6">Secure public record verification</footer>
</body>
</html>